version: "3"
services: 
  esio-app: 
    container_name: esio-app
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: always
    volumes:
      - ./:/usr/src/server
    environment:
      NODE_ENV: development
      NODE_PORT: 3000
      NODE_HOST: http://gameshowbrasil.com.br
      MONGO_PORT: 27017
      MONGO_HOST: esio-mongo
      MONGO_DATABASE: esiodb
    ports: 
      - "3000:3000"
    depends_on:
      - esio-mongo
    networks: 
      - esionetwork
  esio-mongo: 
    container_name: esio-mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports: 
      - "27017:27017"
    networks: 
      - esionetwork
networks: 
  esionetwork:
    driver: bridge